project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links: [repo]
  resources:
    - web/transition_matrices/**

bibliography:
  - research.bib

wrap: preserve

execute:
  eval: false

engines: [julia]
